# Introduction

## Présentation globale du projet 

Afin de gérer un massif forestier et d'écrire les documents d'aménagement, il
est nécessaire de s'intéresser au contexte de ce massif, dont les enjeux 
patrimoniaux qui y sont présents.
Ces informations (telles que les monuments historiques, les sites inscrits et 
classés, les aligements d'arbres...) se trouvent dans les documents d'urbanisme 
(PLU, PLUi, CC, PSMV) ainsi que dans les SUP (servitudes d'utilité 
publique) et les SCOT (Schémas de Cohérence Territoriale), et sont regroupées 
sur le géoportail de l'urbanisme. 

## Justification du besoin des données relatives aux enjeux patrimoniaux

Il est nécessaire de s'intéresser aux enjeux patrimoniaux d'un massif forestier 
car il en découle des contraintes voire des interdictions.
En effet, chaque prescription ou information de document d'urbanisme et chaque
servitude d'utilité publique est lié à un article de loi ou à un réglement des
codes forestier, de l'urbanisme, du patrimoine ou de l'environnement, qui en 
stipule les conséquences. 
Par exemple, une prescription ayant trait au patrimoine bâti ou paysager à 
protéger est liée à l'article L151-19 du code de l'urbanisme, qui stipule qu'il 
est obligatoire d'assurer leur préservation, leur conservation ou leur 
restauration. 

## Description des documents d'aménagements (et SUP)


## Problématique 

Puisqu'il est nécessaire de s'intéresser aux enjeux patrimoniaux et que les 
informations qui y sont relatives sont regroupées sur le géoportail de 
l'urbanisme, il est possible et souhaitable d'automatiser la recherche de ces 
informations. 




Les enjeux patrimoniaux sont utiles pour l'aménagement forestier. Ces informations (telles que les monuments historiques, les sites inscrits et classés, les aligements d'arbres...) se trouvent dans les documents d'urbanisme. Parmi eux, le plan local d'urbanisme (PLU) est le principal document de planification à l’échelle
communale ou intercommunale. Les schémas de cohérence territoriale (SCOT) assurent la cohérence des PLU à l'échelle intercommunale ou régionale. En cas d'absence de PLU, c'est le règlement national d'urbanisme (RNU) qui s'applique. Certaines communes ne disposant pas de PLU établissent une carte communale (CC) pour fixer les règles d'urbanisme. Les enjeux patrimoniaux peuvent aussi être décrits dans des plans de sauvegarde et de mise en valeur (PSMV) de sites historiques et architecturaux.

Les zones de servide d'utilité publique (SUP)

