# **Rapport du projet enjeux patrimoniaux**

# Auteurs : Ninon Delattre, Adèle Desaint, Sylvain Giraudo, Cyril Guillaumant, Louise Rovel # Date : 13/09/2024

# Introduction

## Présentation globale du projet 

Afin de gérer un massif forestier et d'écrire les documents d'aménagement, il
est nécessaire de s'intéresser au contexte de ce massif, dont aux enjeux 
patrimoniaux qui y sont présents. 
Ces informations (telles que les monuments historiques, les sites inscrits et 
classés, les aligements d'arbres...) se trouvent dans les documents d'urbanisme 
(PLU, PLUi, CC, PSMV) ainsi que dans les SUP (servitudes d'utilité 
publique) et les SCOT (Schémas de Cohérence Territoriale), et sont regroupées 
sur le géoportail de l'urbanisme. 

## Justification du besoin des données relatives aux enjeux patrimoniaux

Il est nécessaire de s'intéresser aux enjeux patrimoniaux d'un massif forestier 
car il en découle des contraintes voire des interdictions.
Par exemple, l'existance d'une SUP dans un massif forestier peut entrainer 
l'interdiction de l'engagement ou de la poursuite de travaux. 
(source : https://www.geoportail-urbanisme.gouv.fr/info-general/ 
Il est de même avec la présence d'une presciption du Plan Local d'Urbanisme (PLU). 

## Description des documents d'aménagements (et SUP)
## Problématique 




Les enjeux patrimoniaux sont utiles pour l'aménagement forestier. Ces informations (telles que les monuments historiques, les sites inscrits et classés, les aligements d'arbres...) se trouvent dans les documents d'urbanisme. Parmi eux, le plan local d'urbanisme (PLU) est le principal document de planification à l’échelle
communale ou intercommunale. Les schémas de cohérence territoriale (SCOT) assurent la cohérence des PLU à l'échelle intercommunale ou régionale. En cas d'absence de PLU, c'est le règlement national d'urbanisme (RNU) qui s'applique. Certaines communes ne disposant pas de PLU établissent une carte communale (CC) pour fixer les règles d'urbanisme. Les enjeux patrimoniaux peuvent aussi être décrits dans des plans de sauvegarde et de mise en valeur (PSMV) de sites historiques et architecturaux.

Les zones de servide d'utilité publique (SUP)


# Matériel et Méthode

## Utilisation du géoportail de l'urbanisme et tri des données utiles
## Packages R : happign, mapedit, sf (terra ?)
## Autre methode : flux WFS du geoportail de l'urbanisme
## Méthode de réalisation de la fonction : plusieurs fonctions puis aggrégation 
 
# Résultats

## Liste finale des données utiles dans les documents d'aménagement
## Les différentes fonctions réalisées selon la source de données
## Fonction finale et choix de l'utilisateur
## Les dyfonctionnement de la récupération par flux WFS
## Affichage des données récupérées

# Discussion-Conclusion

## Autres données utiles récupérables par le geoportail, non relatives aux enjeux patrimoniaux (enjeux ecologiques => code de sylvain, mais aussi autres : ex richesse du sol, + possibilité de meilleur tri avec les sous codes)
## Possibilité de meilleur affichage des données récupérées
## Conclusion

# Bibliographie
# Module-R-Projet-3

Lien des standard des différents documents d'urbanisme :
https://cnig.gouv.fr/ressources-dematerialisation-documents-d-urbanisme-a2732.html

Lien code alphanumérique SUP : 
https://www.geoinformations.developpement-durable.gouv.fr/fichier/pdf/tableau_sup_codes_alpha-numerique_maj_20_06_24_2_cle5b12c4.pdf?arg=177836384&cle=d45a3272d7cdbd4f794a17e20e04a63590fc6a8b&file=pdf%2Ftableau_sup_codes_alpha-numerique_maj_20_06_24_2_cle5b12c4.pdf

Lien code SUP
https://www.geoinformations.developpement-durable.gouv.fr/fichier/pdf/tableau_alpha-numerique_des_supet_base_legale_maj_20_06_24_2_cle7dbc5e.pdf?arg=177836385&cle=0ef0d333b5d4e35418b5f3b71d2d3849a002c26f&file=pdf%2Ftableau_alpha-numerique_des_supet_base_legale_maj_20_06_24_2_cle7dbc5e.pdf
